name: "[master]-nightly"

on:
  schedule:
    - cron: "30 0 * * *"

jobs:
  qemux86:
    name: "build"
    env:
      DISTRO: scatest
      PYTHONIOENCODING: utf8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      BUILD_EXPORT: 1
      SCM_BRANCH: master
      BUILD_GLIBC: 1
      BUILD_KERNEL: 1
      BUILD_MAXRUNTIME: 21000

    runs-on: ubuntu-latest

    strategy:
      matrix:
        testset: [standard_01, standard_02, standard_03, metaoe, metaclang, metaruby]
        include:
        - testset: standard_01
          BUILD_PARAMFILE: standard_01
          BUILD_QEMUSYSTEM: 0
        - testset: standard_02
          BUILD_PARAMFILE: standard_02
          BUILD_QEMUSYSTEM: 0
        - testset: standard_03
          BUILD_PARAMFILE: standard_03
          BUILD_QEMUSYSTEM: 1

    container:
      image: privkweihmann/yocto-sca-minimal:latest
      env:
        WORKSPACE: /opt/build
        TOPDIR: /opt/build
        TEMPLATECONF: /opt/build/sources/meta-sca/conf/variant/scatest-qemux86-64/
      volumes:
        - ${{ github.workspace }}:/opt/build
      options: --privileged

    steps:
      - name: setup (container)
        uses: priv-kweihmann/meta-sca-ci-utils/preparecontainer@latest
      - name: checkout (poky)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: git://git.yoctoproject.org/poky.git
          branch: ${{ env.SCM_BRANCH }}
          add-layer: "0"
      - name: checkout (meta-sca)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: https://github.com/priv-kweihmann/meta-sca.git
          branch: ${{ env.SCM_BRANCH }}
      - name: setup (bitbake config)
        uses: priv-kweihmann/meta-sca-ci-utils/addvar@latest
        with:
          variable: SCA_AVAILABLE_MODULES
          value: /opt/build/sources/meta-sca/test/lang_${{ matrix.BUILD_PARAMFILE }}.txt
      - if: env.BUILD_GLIBC == '1'
        name: build (glibc)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: glibc
      - if: env.BUILD_KERNEL == '1'
        name: build (kernel)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: linux-yocto
      - if: matrix.SCM_LAYER_ENABLE_CLANG == '1'
        name: build (clang)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: clang-native
      - if: matrix.BUILD_QEMUSYSTEM == '1'
        name: build (qemu-system)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: qemu-system-native
      - name: setup (rm_work_and_downloads)
        uses: priv-kweihmann/meta-sca-ci-utils/addvar@latest
        with:
          variable: INHERIT
          operation: " += "
          value: rm_work_and_downloads
      - name: build (sca-modules)
        uses: priv-kweihmann/meta-sca-ci-utils/buildmodules@latest
        with:
          parameter-file: ${{ matrix.BUILD_PARAMFILE }}
      - name: test (sca results)
        uses: priv-kweihmann/meta-sca-ci-utils/testresults@latest
        with:
          parameter-file: ${{ matrix.BUILD_PARAMFILE }}
      - if: env.BUILD_EXPORT == '1'
        name: checkout (webpage)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: https://github.com/priv-kweihmann/priv-kweihmann.github.io.git
          branch: master
          add-layer: "0"
          remove-git: "0"
      - if: env.BUILD_EXPORT == '1'
        name: build (webpage)
        uses: priv-kweihmann/meta-sca-ci-utils/exportresults@latest
        with:
          parameter-file: ${{ matrix.BUILD_PARAMFILE }}
          branch: ${{ env.SCM_BRANCH }}
          deploy-token: ${{ secrets.WEBDEPLOY }}
