name: "Package check"

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  qemux86:
    name: "build"
    env:
      DISTRO: scatest
      SCM_BRANCH_META_CLANG: master
      SCM_BRANCH_META_OE: master
      SCM_BRANCH: master
      SCM_LAYER_ENABLE_CLANG: 0
      SCM_LAYER_ENABLE_METAOE: 0
      BUILD_MAXRUNTIME: 21000
      PYTHONIOENCODING: utf8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8

    runs-on: ubuntu-latest

    container:
      image: privkweihmann/yocto-sca-minimal:latest
      env:
        WORKSPACE: /opt/build
        TOPDIR: /opt/build
        TEMPLATECONF: /opt/build/sources/meta-sca/conf/variant/scatest-qemux86-64/
      volumes:
        - ${{ github.workspace }}:/opt/build
      options: --privileged

    steps:
      - name: setup (container)
        uses: priv-kweihmann/meta-sca-ci-utils/preparecontainer@latest
      - name: checkout (poky)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: git://git.yoctoproject.org/poky.git
          branch: ${{ env.SCM_BRANCH }}
          add-layer: "0"
      - name: checkout (meta-sca)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: https://github.com/priv-kweihmann/meta-sca.git
          branch: master
      - if: env.SCM_LAYER_ENABLE_METAOE == '1'
        name: checkout (meta-openembedded)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: git://git.openembedded.org/meta-openembedded
          branch: ${{ env.SCM_BRANCH_META_OE }}
          add-layer-suffix: /meta-oe
      - if: env.SCM_LAYER_ENABLE_CLANG == '1'
        name: checkout (meta-clang)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: https://github.com/kraj/meta-clang.git
          branch: ${{ env.SCM_BRANCH_META_CLANG }}
      - name: setup (bitbake config)
        uses: priv-kweihmann/meta-sca-ci-utils/addvar@latest
        with:
          variable: BB_DANGLINGAPPENDS_WARNONLY
          value: 1
      - name: setup layer prio (bitbake config)
        uses: priv-kweihmann/meta-sca-ci-utils/addvar@latest
        with:
          variable: BBFILE_PRIORITY_meta-sca
          value: 100
      - name: setup layer preference (bitbake config)
        uses: priv-kweihmann/meta-sca-ci-utils/addvar@latest
        with:
          variable: SCA_DEFAULT_PREFERENCE
          value: 0
      - name: check (packages)
        uses: priv-kweihmann/meta-sca-ci-utils/packagecheck@latest
        with:
          backoff-time: 60
          blacklist: "blacklist.txt"
          deploy-token: ${{ secrets.WEBDEPLOY }}
          user: "priv-kweihmann"
